# Generated by Django 3.2.4 on 2021-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_level', models.CharField(max_length=250)),
                ('levels_content', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_description', models.CharField(max_length=250)),
                ('course_duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('modules_content', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modules_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=250)),
                ('content_levels', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('price_per_month', models.CharField(max_length=250)),
            ],
        ),
    ]
