# Generated by Django 3.2.4 on 2021-06-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Modules_content',
        ),
        migrations.RenameField(
            model_name='content_type',
            old_name='contents_level',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='course_name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='content_type',
            name='levels_content',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='modules_content',
        ),
        migrations.AddField(
            model_name='modules',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='models_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modules'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.content_type'),
        ),
        migrations.AddField(
            model_name='content',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
