# Generated by Django 3.2.4 on 2021-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210729_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='content_type',
            options={'verbose_name': 'Тип контента', 'verbose_name_plural': 'Типы контента'},
        ),
    ]
